// DRACONIA - EXPLORATION ENRICHIE 🗺️🐉
(function(){
const KEY="draconiaExplorationZone";
const zones={forest:{name:"Forêt ancienne",icon:"🌲",description:"Nature, Air et Terre sont plus fréquents.",elements:["Nature","Air","Terre"]},lake:{name:"Lac brumeux",icon:"🌊",description:"Eau, Glace et Air sont plus fréquents.",elements:["Eau","Glace","Air"]},mountain:{name:"Montagnes ardentes",icon:"⛰️",description:"Feu, Terre et Foudre sont plus fréquents.",elements:["Feu","Terre","Foudre"]},ruins:{name:"Ruines célestes",icon:"🏛️",description:"Ombre, Lumière et Cosmique y apparaissent plus souvent.",elements:["Ombre","Lumière","Cosmique"]}};
let selectedZone=localStorage.getItem(KEY);if(!zones[selectedZone])selectedZone="forest";
const rarityWeights={"Commun":5,"Peu commun":3.6,"Rare":2,"Épique":1,"Légendaire":.35};
const weatherMap={sun:"Lumière",water:"Eau",lightning:"Foudre",ice:"Glace",shadow:"Ombre",air:"Air",nature:"Nature"};
function perks(){return typeof window.draconiaPlayerPerks==="function"?window.draconiaPlayerPerks():{explorationBonus:0,rarityBonus:1}}
function styles(){if(document.getElementById("draconia-exploration-styles"))return;const s=document.createElement("style");s.id="draconia-exploration-styles";s.textContent=`.exploration-zones{margin:18px 0 16px;text-align:left}.exploration-zones-title{margin:0 0 9px;font-size:13px;font-weight:900;opacity:.78}.exploration-zone-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.exploration-zone{border:1px solid rgba(167,139,250,.25);border-radius:15px;padding:11px;background:linear-gradient(145deg,#241b4f,#162447);color:#f8f7ff;text-align:left}.exploration-zone.selected{border-color:#a78bfa;box-shadow:0 0 0 2px rgba(124,58,237,.18)}.exploration-zone strong,.exploration-zone small{display:block}.exploration-zone small{margin-top:3px;font-size:10px;opacity:.72}.exploration-zone-icon{font-size:24px;margin-bottom:5px}.exploration-current{margin-top:10px;padding:9px 11px;border-radius:12px;background:rgba(124,58,237,.08);font-size:12px}`;document.head.appendChild(s)}
function weatherElement(){return typeof getWeatherBonus==="function"?weatherMap[getWeatherBonus()]||null:null}
function renderZones(){styles();const card=document.querySelector(".egg-card");if(!card)return;let c=document.getElementById("exploration-zones");if(!c){c=document.createElement("div");c.id="exploration-zones";c.className="exploration-zones";const b=document.getElementById("egg-button");if(b)b.insertAdjacentElement("beforebegin",c);else card.appendChild(c)}const w=weatherElement(),z=zones[selectedZone];c.innerHTML=`<p class="exploration-zones-title">🗺️ Choisis une zone à explorer</p><div class="exploration-zone-grid">${Object.entries(zones).map(([id,x])=>`<button class="exploration-zone ${id===selectedZone?"selected":""}" data-zone="${id}"><div class="exploration-zone-icon">${x.icon}</div><strong>${x.name}</strong><small>${x.description}</small></button>`).join("")}</div><div class="exploration-current"><strong>${z.icon} ${z.name}</strong><br>${w?`🌦️ Météo favorable aux dragons ${w}.`:"🌦️ La météo peut influencer les rencontres."}</div>`;c.querySelectorAll("[data-zone]").forEach(b=>b.onclick=()=>{selectedZone=b.dataset.zone;localStorage.setItem(KEY,selectedZone);renderZones()})}
function pickDragon(){if(typeof dragons==="undefined"||!dragons.length)return null;const z=zones[selectedZone],w=weatherElement(),p=perks(),arr=dragons.map(d=>{let weight=rarityWeights[d.rarity]||1;if(z.elements.includes(d.element))weight*=3;if(w===d.element)weight*=2.2;if(typeof isNight==="function"&&isNight()&&d.element==="Ombre")weight*=1.7;if(["Rare","Épique","Légendaire"].includes(d.rarity))weight*=p.rarityBonus||1;return{d,weight}}),total=arr.reduce((a,x)=>a+x.weight,0);let r=Math.random()*total;for(const x of arr){r-=x.weight;if(r<=0)return x.d}return arr[arr.length-1].d}
function eventReward(message){const roll=Math.random();if(roll<.38&&typeof player!=="undefined"){const coins=8+Math.floor(Math.random()*13);player.coins=(Number(player.coins)||0)+coins;if(typeof savePlayer==="function")savePlayer();if(typeof updatePlayerDisplay==="function")updatePlayerDisplay();message.textContent=`💰 Tu découvres une petite cache : +${coins} pièces !`;return}const pool=selectedZone==="lake"?["fish","herb"]:selectedZone==="mountain"?["mushroom","meat"]:selectedZone==="ruins"?["insect","mushroom"]:["apple","berry","herb","insect"];const r=pool[Math.floor(Math.random()*pool.length)],labels={fish:"🐟 poisson",herb:"🌿 herbe",mushroom:"🍄 champignon",meat:"🍖 viande",insect:"🐛 insecte",apple:"🍎 pomme",berry:"🍓 baie"};if(typeof addResource==="function")addResource(r,1);message.textContent=`🎒 Exploration utile : +1 ${labels[r]} trouvé !`}
function find(){const b=document.getElementById("egg-button"),m=document.getElementById("egg-message"),z=zones[selectedZone];if(typeof window.draconiaHasActiveEgg==="function"&&window.draconiaHasActiveEgg()){if(m)m.textContent="🥚 Un œuf est déjà en incubation.";return}if(b)b.disabled=true;if(m)m.textContent=`${z.icon} Exploration de ${z.name}...`;setTimeout(()=>{const p=perks(),roll=Math.random(),eggChance=.42+(p.explorationBonus||0),eventChance=.38;if(roll<eggChance){const d=pickDragon();if(d&&typeof window.draconiaReceiveEgg==="function"&&window.draconiaReceiveEgg(d,z.name)){if(m)m.textContent=`🥚 Tu as trouvé un œuf ${d.element} • ${d.rarity} !`;return}}else if(roll<eggChance+eventChance){if(m)eventReward(m);if(b)b.disabled=false;return}if(m)m.textContent=`🍃 Tu explores ${z.name}, mais tu ne trouves rien cette fois.`;if(b)b.disabled=false},850)}
function install(){renderZones();window.findEgg=find;window.renderExplorationZones=renderZones}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
})();