// DRACONIA - MARCHÉ DES RESSOURCES 🏪
(function(){
const items=[
{r:"apple",i:"🍎",n:"Pomme",p:5},{r:"berry",i:"🍓",n:"Baie",p:5},{r:"herb",i:"🌿",n:"Herbe",p:6},{r:"insect",i:"🐛",n:"Insecte",p:8},{r:"mushroom",i:"🍄",n:"Champignon",p:10},{r:"vegetable",i:"🥕",n:"Légume",p:10},{r:"fish",i:"🐟",n:"Poisson",p:12},{r:"meat",i:"🍖",n:"Viande",p:15}
];
function styles(){if(document.getElementById("market-style"))return;const s=document.createElement("style");s.id="market-style";s.textContent=`.market{margin-top:22px;padding:16px;border-radius:20px;border:1px solid rgba(245,158,11,.25);background:rgba(245,158,11,.08)}.market-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.market-head h2{margin:3px 0}.market-wallet{padding:8px 11px;border-radius:12px;background:rgba(245,158,11,.14);font-weight:900;white-space:nowrap}.market-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:14px}.market-item{display:flex;align-items:center;gap:9px;padding:11px;border-radius:15px;background:rgba(255,255,255,.72)}.market-icon{font-size:24px}.market-info{flex:1;min-width:0}.market-info strong,.market-info small{display:block}.market-info small{font-size:11px;opacity:.7}.market-buy{border:0;border-radius:10px;padding:8px 9px;background:#f59e0b;color:#fff;font-weight:900}.market-buy:disabled{opacity:.4}.market-msg{min-height:20px;margin-top:10px;text-align:center;font-size:12px;font-weight:800}@media(max-width:520px){.market-grid{grid-template-columns:1fr}.market-head{display:block}.market-wallet{display:inline-block;margin-top:8px}}`;document.head.appendChild(s)}
function panel(){const page=document.getElementById("inventory-page");if(!page)return null;let p=document.getElementById("draconia-market");if(!p){p=document.createElement("section");p.id="draconia-market";p.className="market";page.appendChild(p)}return p}
function render(){styles();const p=panel();if(!p||typeof player==="undefined"||typeof inventory==="undefined")return;const c=Math.max(0,Number(player.coins)||0);p.innerHTML=`<div class="market-head"><div><p class="small-title">DÉPANNAGE</p><h2>🏪 Marché de Draconia</h2><p>Achète un ingrédient s'il t'en manque. Récolter reste plus avantageux.</p></div><div class="market-wallet">💰 ${c}</div></div><div class="market-grid">${items.map(x=>`<div class="market-item"><div class="market-icon">${x.i}</div><div class="market-info"><strong>${x.n}</strong><small>Dans le sac : ${Number(inventory[x.r])||0}</small></div><button class="market-buy" data-market="${x.r}" ${c<x.p?"disabled":""}>${x.p} 💰</button></div>`).join("")}</div><div id="market-msg" class="market-msg"></div>`;p.querySelectorAll("[data-market]").forEach(b=>b.onclick=()=>buy(b.dataset.market))}
function buy(r){const x=items.find(v=>v.r===r);if(!x)return;const c=Number(player.coins)||0;if(c<x.p)return;player.coins=c-x.p;inventory[r]=(Number(inventory[r])||0)+1;if(typeof savePlayer==="function")savePlayer();if(typeof saveInventory==="function")saveInventory();if(typeof updatePlayerDisplay==="function")updatePlayerDisplay();if(typeof updateInventoryDisplay==="function")updateInventoryDisplay();render();const m=document.getElementById("market-msg");if(m)m.textContent=`${x.i} +1 ${x.n} acheté pour ${x.p} 💰`}
window.renderDraconiaMarket=render;window.buyMarketItem=buy;if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",render,{once:true});else render();
})();