(function(){
const M={3:{title:"Explorateur",icon:"🧭",bonus:40,perk:"+5% de chance de trouver quelque chose en exploration"},5:{title:"Gardien",icon:"🛡️",bonus:75,perk:"Incubation des nouveaux œufs 10% plus rapide"},10:{title:"Maître",icon:"🌟",bonus:150,perk:"Meilleure chance de rencontrer des dragons rares"},15:{title:"Légende",icon:"👑",bonus:250,perk:"Bonus maximum d'exploration et d'incubation"}};
const BASE=20;
function getPlayer(){return typeof player!=="undefined"&&player?player:null}
function rank(level){if(level>=15)return{title:"Légende",icon:"👑"};if(level>=10)return{title:"Maître",icon:"🌟"};if(level>=5)return{title:"Gardien",icon:"🛡️"};if(level>=3)return{title:"Explorateur",icon:"🧭"};return{title:"Novice",icon:"🌱"}}
function reward(level){return BASE+(M[level]?.bonus||0)}
function nextMilestone(level){return Object.keys(M).map(Number).find(n=>n>level)||null}
function currentPerk(level){if(level>=15)return M[15].perk;if(level>=10)return M[10].perk;if(level>=5)return M[5].perk;if(level>=3)return M[3].perk;return "Monte au niveau 3 pour obtenir ton premier bonus."}
function styles(){if(document.getElementById("player-progression-style"))return;const s=document.createElement("style");s.id="player-progression-style";s.textContent=`.player-progression-info{margin-top:10px;padding:10px 12px;border-radius:14px;background:rgba(124,58,237,.08);font-size:12px;line-height:1.45}.player-progression-info strong{display:block;margin-bottom:3px}.player-perk{margin-top:5px;font-weight:800;color:#6d28d9}.player-level-toast{position:fixed;top:16px;left:50%;z-index:3400;width:min(calc(100% - 28px),420px);transform:translate(-50%,-20px);opacity:0;padding:14px;border-radius:18px;background:linear-gradient(135deg,#5b21b6,#8b5cf6);color:#fff;box-shadow:0 14px 30px rgba(0,0,0,.25);transition:.25s;pointer-events:none}.player-level-toast.show{transform:translate(-50%,0);opacity:1}.player-level-toast strong,.player-level-toast span,.player-level-toast small{display:block}.player-level-toast span{font-weight:900;margin:3px 0}`;document.head.appendChild(s)}
function render(){styles();const card=document.querySelector(".level-card"),p=getPlayer();if(!card||!p)return;let box=document.getElementById("player-progression-info");if(!box){box=document.createElement("div");box.id="player-progression-info";box.className="player-progression-info";card.appendChild(box)}const l=Number(p.level)||1,r=rank(l),next=nextMilestone(l);box.innerHTML=`<strong>${r.icon} Rang : ${r.title}</strong><span>🎁 Prochain niveau : +${reward(l+1)} pièces</span><div class="player-perk">✨ Bonus actuel : ${currentPerk(l)}</div>${next?`<span>🏆 Prochain palier : niveau ${next} • ${M[next].icon} ${M[next].title}</span>`:`<span>👑 Tous les paliers du prototype sont débloqués.</span>`}`}
function toast(level,coins){styles();let t=document.getElementById("player-level-toast");if(!t){t=document.createElement("div");t.id="player-level-toast";t.className="player-level-toast";document.body.appendChild(t)}const m=M[level];t.innerHTML=`<strong>⭐ Niveau joueur ${level} !</strong><span>💰 +${coins} pièces</span>${m?`<small>${m.icon} ${m.title} • ${m.perk}</small>`:""}`;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),3500)}
function install(){const p=getPlayer();if(typeof addPlayerXP!=="function"||!p)return false;if(addPlayerXP.__playerProgression)return true;const original=addPlayerXP;const wrapped=function(amount){const before=Number(p.level)||1,result=original.apply(this,arguments),after=Number(p.level)||1;if(after>before){let total=0;for(let l=before+1;l<=after;l++)total+=reward(l);p.coins=(Number(p.coins)||0)+total;if(typeof savePlayer==="function")savePlayer();if(typeof updatePlayerDisplay==="function")updatePlayerDisplay();toast(after,total)}render();return result};wrapped.__playerProgression=true;window.addPlayerXP=wrapped;render();return true}
window.draconiaPlayerPerks=function(){const p=getPlayer(),l=p?Number(p.level)||1:1;return{explorationBonus:l>=15?.12:l>=3?.05:0,hatchMultiplier:l>=15?.8:l>=5?.9:1,rarityBonus:l>=15?1.35:l>=10?1.18:1}};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{if(!install()){const i=setInterval(()=>{if(install())clearInterval(i)},250)}},{once:true});else if(!install()){const i=setInterval(()=>{if(install())clearInterval(i)},250)}
window.renderPlayerProgression=render;
})();