(function(){
const M={3:{title:"Explorateur",icon:"🧭",bonus:40},5:{title:"Gardien",icon:"🛡️",bonus:75},10:{title:"Maître",icon:"🌟",bonus:150},15:{title:"Légende",icon:"👑",bonus:250}};
const BASE=20;
function rank(level){if(level>=15)return{title:"Légende",icon:"👑"};if(level>=10)return{title:"Maître",icon:"🌟"};if(level>=5)return{title:"Gardien",icon:"🛡️"};if(level>=3)return{title:"Explorateur",icon:"🧭"};return{title:"Novice",icon:"🌱"}}
function reward(level){return BASE+(M[level]?.bonus||0)}
function nextMilestone(level){return Object.keys(M).map(Number).find(n=>n>level)||null}
function styles(){if(document.getElementById("player-progression-style"))return;const s=document.createElement("style");s.id="player-progression-style";s.textContent=`.player-progression-info{margin-top:10px;padding:10px 12px;border-radius:14px;background:rgba(124,58,237,.08);font-size:12px;line-height:1.45}.player-progression-info strong{display:block;margin-bottom:3px}.player-level-toast{position:fixed;top:16px;left:50%;z-index:3400;width:min(calc(100% - 28px),420px);transform:translate(-50%,-20px);opacity:0;padding:14px;border-radius:18px;background:linear-gradient(135deg,#5b21b6,#8b5cf6);color:#fff;box-shadow:0 14px 30px rgba(0,0,0,.25);transition:.25s;pointer-events:none}.player-level-toast.show{transform:translate(-50%,0);opacity:1}.player-level-toast strong,.player-level-toast span,.player-level-toast small{display:block}.player-level-toast span{font-weight:900;margin:3px 0}`;document.head.appendChild(s)}
function render(){styles();const card=document.querySelector(".level-card");if(!card||!window.player)return;let box=document.getElementById("player-progression-info");if(!box){box=document.createElement("div");box.id="player-progression-info";box.className="player-progression-info";card.appendChild(box)}const l=Number(player.level)||1,r=rank(l),next=nextMilestone(l);box.innerHTML=`<strong>${r.icon} Rang : ${r.title}</strong><span>🎁 Prochain niveau : +${reward(l+1)} pièces</span>${next?`<br><span>🏆 Prochain palier : niveau ${next} • ${M[next].icon} ${M[next].title} • +${M[next].bonus} bonus</span>`:`<br><span>👑 Tous les paliers du prototype sont débloqués.</span>`}`}
function toast(level,coins){styles();let t=document.getElementById("player-level-toast");if(!t){t=document.createElement("div");t.id="player-level-toast";t.className="player-level-toast";document.body.appendChild(t)}const m=M[level];t.innerHTML=`<strong>⭐ Niveau joueur ${level} !</strong><span>💰 +${coins} pièces</span>${m?`<small>${m.icon} Nouveau rang : ${m.title}</small>`:""}`;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),3500)}
function install(){if(typeof addPlayerXP!=="function"||!window.player)return false;if(addPlayerXP.__playerProgression)return true;const original=addPlayerXP;const wrapped=function(amount){const before=Number(player.level)||1;const result=original.apply(this,arguments);const after=Number(player.level)||1;if(after>before){let total=0;for(let l=before+1;l<=after;l++)total+=reward(l);player.coins=(Number(player.coins)||0)+total;if(typeof savePlayer==="function")savePlayer();if(typeof updatePlayerDisplay==="function")updatePlayerDisplay();toast(after,total)}render();return result};wrapped.__playerProgression=true;window.addPlayerXP=wrapped;render();return true}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{if(!install()){const i=setInterval(()=>{if(install())clearInterval(i)},250)}},{once:true});else if(!install()){const i=setInterval(()=>{if(install())clearInterval(i)},250)}
window.renderPlayerProgression=render;
})();