const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const flamio={id:'dragon-feu',name:'Flamio',element:'Feu',icon:'🔥🐉'};
const noctis={id:'dragon-ombre',name:'Noctis',element:'Ombre',icon:'🌑🐉'};
const context={ownedDragons:[{id:'dragon-feu',level:9},{id:'dragon-ombre',level:9}]};
vm.createContext(context);vm.runInContext(fs.readFileSync('dragonart.js','utf8'),context);
assert(context.dragonArtwork(flamio).includes('assets/flamio.webp'),'image normale de Flamio avant le niveau 10');
context.ownedDragons[0].level=10;
assert(context.dragonArtwork(flamio).includes('assets/flamio-level-10-aura.webp'),'image avec aura de Flamio au niveau 10');
assert(context.dragonArtwork(flamio,'egg').includes('assets/flamio-egg.webp'),'l’œuf de Flamio reste inchangé');
assert(context.dragonArtwork(noctis).includes('assets/shadow-dragon.webp'),'image normale de Noctis avant le niveau 10');
context.ownedDragons[1].level=10;
assert(context.dragonArtwork(noctis).includes('assets/noctis-level-10-aura.webp'),'image avec aura de Noctis au niveau 10');
assert(context.dragonArtwork(noctis,'egg').includes('assets/shadow-egg.webp'),'l’œuf de Noctis reste inchangé');
console.log('Auras Flamio et Noctis : images normales niveaux 1-9 et variantes transparentes au niveau 10 OK');
