const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const flamio={id:'dragon-feu',name:'Flamio',element:'Feu',icon:'🔥🐉'};
const noctis={id:'dragon-ombre',name:'Noctis',element:'Ombre',icon:'🌑🐉'};
const zephyr={id:'dragon-air',name:'Zéphyr',element:'Air',icon:'🌪️🐉'};
const aquaria={id:'dragon-eau',name:'Aquaria',element:'Eau',icon:'🌊🐉'};
const lightning={id:'dragon-foudre',name:'Dragon de Foudre',element:'Foudre',icon:'⚡🐉'};
const light={id:'dragon-lumiere',name:'Dragon de Lumière',element:'Lumière',icon:'☀️🐉'};
const context={ownedDragons:[{id:'dragon-feu',level:9},{id:'dragon-ombre',level:9},{id:'dragon-air',level:9},{id:'dragon-eau',level:9},{id:'dragon-foudre',level:9},{id:'dragon-lumiere',level:9}]};
vm.createContext(context);vm.runInContext(fs.readFileSync('dragonart.js','utf8'),context);
assert(context.dragonArtwork(flamio).includes('assets/flamio.webp'),'image normale de Flamio avant le niveau 10');
context.ownedDragons[0].level=10;
assert(context.dragonArtwork(flamio).includes('assets/flamio-level-10-aura.webp'),'image avec aura de Flamio au niveau 10');
assert(context.dragonArtwork(flamio,'egg').includes('assets/flamio-egg.webp'),'l’œuf de Flamio reste inchangé');
assert(context.dragonArtwork(noctis).includes('assets/shadow-dragon.webp'),'image normale de Noctis avant le niveau 10');
context.ownedDragons[1].level=10;
assert(context.dragonArtwork(noctis).includes('assets/noctis-level-10-aura.webp'),'image avec aura de Noctis au niveau 10');
assert(context.dragonArtwork(noctis,'egg').includes('assets/shadow-egg.webp'),'l’œuf de Noctis reste inchangé');
assert(context.dragonArtwork(zephyr).includes('assets/air-dragon.webp'),'image normale de Zéphyr avant le niveau 10');
context.ownedDragons[2].level=10;
assert(context.dragonArtwork(zephyr).includes('assets/zephyr-level-10-aura.webp'),'image avec aura de Zéphyr au niveau 10');
assert(context.dragonArtwork(zephyr,'egg').includes('assets/air-egg.webp'),'l’œuf de Zéphyr reste inchangé');
assert(context.dragonArtwork(aquaria).includes('assets/water-dragon.webp'),'image normale d’Aquaria avant le niveau 10');
context.ownedDragons[3].level=10;
assert(context.dragonArtwork(aquaria).includes('assets/aquaria-level-10-aura.webp'),'image avec aura d’Aquaria au niveau 10');
assert(context.dragonArtwork(aquaria,'egg').includes('assets/water-egg.webp'),'l’œuf d’Aquaria reste inchangé');
assert(context.dragonArtwork(lightning).includes('assets/lightning-dragon.webp'),'image normale du dragon de Foudre avant le niveau 10');
context.ownedDragons[4].level=10;
assert(context.dragonArtwork(lightning).includes('assets/lightning-level-10-aura.webp'),'image avec aura du dragon de Foudre au niveau 10');
assert(context.dragonArtwork(lightning,'egg').includes('assets/lightning-egg.webp'),'l’œuf de Foudre reste inchangé');
assert(context.dragonArtwork(light).includes('assets/light-dragon.webp'),'image normale du dragon de Lumière avant le niveau 10');
context.ownedDragons[5].level=10;
assert(context.dragonArtwork(light).includes('assets/light-level-10-aura.webp'),'image avec aura du dragon de Lumière au niveau 10');
assert(context.dragonArtwork(light,'egg').includes('assets/light-egg.webp'),'l’œuf de Lumière reste inchangé');
console.log('Auras des six dragons configurés : images normales niveaux 1-9 et variantes niveau 10 OK');
